### ISSUE TITLE
System.IndexOutOfRangeException: Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by yasserss** [badamczewski/PowerUp#9]
I cant get this tool working i keep getting this error message whenever i try to de-compilea cs file   

`System.IndexOutOfRangeException: Index was outside the bounds of the array.    at PowerUp.Watcher.ILWriter.ToILString(DecompilationUnit unit) in D:\Compilers\PowerUp-main\src\PowerUp.Watcher\ILWriter.cs:line 20    at PowerUp.Watcher.CSharpWatcher.<>c__DisplayClass10_0.<<WatchFile>b__0>d.MoveNext() in D:\Compilers\PowerUp-main\src\PowerUp.Watcher\CSharpWatcher.cs:line 218`

**Comment by yasserss** [comment]
```
=== PowerUP Watcher ===

CSharp Watcher Initialize:
Input File: _code.cs
ASM   File: _out.asm
IL    File: _out.il
CS    File:
[WARNING]: CSharp File doesnt exist
Libs  Path: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.10\
.NET Enviromment variables:
Language  Version: latest
.NET Version: 5.0.13
[RELEASE]
Decompiling: _code.cs
Language Version: 9.0
Writing Errors to: _out.asm, _out.il,
```

my _code.cs code only contain this : 

`void M(){}`

**Comment by badamczewski** [comment]
That's really strange here's my output for the same thing:

![obraz](https://user-images.githubusercontent.com/752380/152318209-b7329208-cb7a-40ec-a2a2-43ef74860937.png)

**Comment by badamczewski** [comment]
Please pull the new version and check if anything has changed. I can't reproduce the issue on my end so I'm guessing what the problem might be. 

The code fails in IL generation but that might not be the core issue since maybe the initial compilation failed and there are no IL tokens to parse at all (it's all speculation on my part).

**Comment by OlegAxenow** [comment]
This is because missing `autocrlf = auto` inside the global `.gitconfig` file, I think.

`.gitattributes` with `* text=auto` for this repo can fix problem, but I am not sure about it (may be better solution exists?).

As a quick ~fix~ hack you can add helper to split code and use them where `Split(Environment.NewLine)` found (`ILToCodeMapProvider.cs` and `ILWriter.cs`):
```
public static class SplitHelper
{
	public static string[] SplitLines(string code)
	{
		if (code == null) throw new ArgumentNullException(nameof(code));
		var lines = code.Split(Environment.NewLine);
		// hack to fight with missing 'autocrlf = auto' in .gitconfig
		if (lines.Length > 0 && lines[0].Contains('\n', StringComparison.Ordinal))
			lines = code.Split('\n');
		return lines;
	}
}
```

**Comment by badamczewski** [comment]
LOL Github closed the issue because of the commit message that I've made. Feel free to continue the discussion here, should the problem be still present.

**Comment by yasserss** [comment]
The last commit fixed the problem thanks you guys . 
Btw amazing tool i love it 🙂
